#!/usr/bin/env python3
import delate_m


def main():
    delate_m.w_connect()


def test():
    # Non-async API
    delate_m.get_timetable('8000261')

    # Async API (low-level)
    async for update in delate_m.get_timetable_updates():
        ...

    # Class based
    c = delate_m.connect()
    c.sub_timetable('8000261')
    async for update in c.updates:
        ...


if __name__ == "__main__":
    main()
